[package]
name = "account-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
solana-client = "3.0.2"
solana-sdk = "3.0.0"
solana-account-decoder = "3.0.2"
dotenvy = "0.15"
# Cargo.toml
spl-token = "3"

