[package]
name = "account-test"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "2.3.8"
solana-sdk = "2.3.8"
solana-account-decoder = "2.3.8"
tokio = { version = "1", features = ["full"] }
